VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsSalon"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public dbl_status As Integer
Public inn As Integer
Public id As Long
Public name As String
Public city_name_geographic As String
Public street As String
Public house As String
Public law_name As String
Public countusr As Integer
Public countusreducated As Integer
Public club As Integer
Public activ_users As Integer
Public com_mreg As String
